# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target "20160331BuDeJie" do
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.5'
pod 'SVProgressHUD', '~> 2.0'
end